# This is a TOML document

title = "Configuration of User Agent"

logfile = "user_auth.log"

[server]
host = "0.0.0.0"
port = 10101

[client]
endpoint_id = 0  # 0: server generating
role = 3  # 1: normal, 2: admin, 3: service
svc_type = 101  # NOTE: between 1 to 255
access_code = "GOE works"
enable_console = true
console_sub_prompt = "UA"

[user_auth]
  [user_auth.database]
  #driver = "sqlite"
  #uri = "user_auth.sqlite"
  driver = "file"
  users_uri = "users.json"
  sessions_uri = "users_sessions.json"
