# This is a TOML document

title = "Configuration of User Account"

logfile = "user_account.log"

[server]
host = "0.0.0.0"
port = 10101

[client]
endpoint_id = 0  # 0: server generating
role = 3  # 1: normal, 2: admin, 3: service
svc_type = 102  # NOTE: between 1 to 255
access_code = "GOE works"
enable_console = true
console_sub_prompt = "UAC"

[user_account]
  [user_account.database]
  driver = "sqlite"
  uri = "database/user_account.sqlite"
