subsystem:
	$(MAKE) -C common
	$(MAKE) -C server
	$(MAKE) -C client

clean:
	$(MAKE) -C common clean
	$(MAKE) -C server clean
	$(MAKE) -C client clean

cleanall:
	$(MAKE) -C common cleanall
	$(MAKE) -C server cleanall
	$(MAKE) -C client cleanall
